import { memo, useCallback, useEffect, useId, useRef, useState, type FocusEvent, type PointerEvent as ReactPointerEvent } from 'react';
import { ChevronRight, CornerUpLeft, Cpu, Undo2 } from 'lucide-react';
import type { Change, Finish, InventoryPayload, SettingsPayload, TipPayload } from '../../../../shared/types.ts';
import { changeSummary } from '../../../../shared/summarize.ts';
import { useStore } from '../../store/store.ts';
import { useCard } from '../../store/selectors.ts';
import { openCard } from '../../lib/router.ts';
import { preload } from '../../lib/images.ts';
import { useLongPress } from '../../lib/useLongPress.ts';
import { cx, fmtDateTime, pluralize, relTime, signed } from '../../lib/format.ts';
import { usePreview, rectOf } from '../cards/previewStore.ts';
import { CardImage } from '../cards/CardImage.tsx';
import { Avatar } from '../ui/Avatar.tsx';
import { Badge, type BadgeTone } from '../ui/Badge.tsx';
import { Button } from '../ui/Button.tsx';

// ---------------------------------------------------------------------------
// kind badge
// ---------------------------------------------------------------------------

export type KindLabel = 'inventory' | 'product' | 'pack' | 'csv' | 'note' | 'undo' | 'tip' | 'tips' | 'prices' | 'fx' | 'catalog' | 'settings';

/** Badge label for a change: inventory rows are split by reason, everything else by kind. */
export function kindOf(c: Change): KindLabel {
  if (c.kind === 'inventory') {
    switch (c.reason) {
      case 'product':
        return 'product';
      case 'pack':
        return 'pack';
      case 'csv':
        return 'csv';
      case 'note':
        return 'note';
      case 'undo':
        return 'undo';
      default:
        return 'inventory';
    }
  }
  return c.kind;
}

const KIND_TONE: Record<KindLabel, BadgeTone> = {
  inventory: 'neutral',
  product: 'accent',
  pack: 'success',
  csv: 'warning',
  note: 'neutral',
  undo: 'outline',
  tip: 'accent',
  tips: 'outline',
  prices: 'outline',
  fx: 'outline',
  catalog: 'outline',
  settings: 'outline',
};

const KIND_TITLE: Record<KindLabel, string> = {
  inventory: 'Manual inventory edit',
  product: 'Product purchase',
  pack: 'Pack mode entry',
  csv: 'CSV import',
  note: 'Card note edited',
  undo: 'Undo of an earlier change',
  tip: 'Card tip edited',
  tips: 'Tips generated by Codex',
  prices: 'Price sync',
  fx: 'Exchange-rate sync',
  catalog: 'Catalog sync',
  settings: 'Settings changed',
};

// ---------------------------------------------------------------------------
// lines (card thumb + prev → new), shared by inventory and tip rows
// ---------------------------------------------------------------------------

export interface FeedLine {
  card_id: string;
  finish?: Finish;
  qty?: number;
  prev_qty?: number;
  note?: string;
  prev_note?: string;
  clamped?: true;
}

/** Lines worth expanding for a change (empty for system rows). */
export function linesOf(c: Change): FeedLine[] {
  if (c.kind === 'inventory') return (c.payload as InventoryPayload).lines;
  if (c.kind === 'tip') return [{ card_id: (c.payload as TipPayload).card_id }];
  return [];
}

const HOVER_DELAY = 120;
const LINE_CAP = 40;

/** One card line: thumb + name + finish + prev → new. Click → drawer; hover/focus → HoverPreview; long-press → sheet. */
function LineRow({ line }: { line: FeedLine }) {
  const card = useCard(line.card_id);
  const show = usePreview((s) => s.show);
  const hide = usePreview((s) => s.hide);
  const openSheet = usePreview((s) => s.openSheet);
  const ref = useRef<HTMLButtonElement>(null);
  const thumbRef = useRef<HTMLSpanElement>(null);
  const hoverTimer = useRef<number | null>(null);

  const clearHover = useCallback(() => {
    if (hoverTimer.current !== null) window.clearTimeout(hoverTimer.current);
    hoverTimer.current = null;
  }, []);
  useEffect(() => clearHover, [clearHover]);

  const anchor = () => thumbRef.current ?? ref.current;
  const onPointerEnter = (e: ReactPointerEvent<HTMLElement>) => {
    if (e.pointerType !== 'mouse' || !card) return;
    void preload(card, 'full');
    clearHover();
    hoverTimer.current = window.setTimeout(() => {
      hoverTimer.current = null;
      const el = anchor();
      if (el) show(line.card_id, rectOf(el), 'mouse');
    }, HOVER_DELAY);
  };
  const onPointerLeave = (e: ReactPointerEvent<HTMLElement>) => {
    if (e.pointerType !== 'mouse') return;
    clearHover();
    hide(line.card_id);
  };
  const onFocus = (e: FocusEvent<HTMLElement>) => {
    if (e.target !== ref.current || !card) return;
    const el = anchor();
    if (el && ref.current.matches(':focus-visible')) show(line.card_id, rectOf(el), 'focus');
  };
  const longPress = useLongPress(() => {
    clearHover();
    openSheet(line.card_id);
  });

  const name = card?.name ?? line.card_id;
  const foil = line.finish === 'foil';
  const hasQty = line.qty !== undefined && line.prev_qty !== undefined;
  const delta = hasQty ? (line.qty as number) - (line.prev_qty as number) : 0;
  const noteChanged = line.prev_note !== undefined && line.prev_note !== line.note;
  const label = `${name}${foil ? ' foil' : ''}${hasQty ? `, ${line.prev_qty} to ${line.qty}` : ''} — open card`;

  return (
    <li>
      <button
        ref={ref}
        type="button"
        aria-label={label}
        onClick={() => {
          clearHover();
          hide(line.card_id);
          openCard(line.card_id);
        }}
        {...longPress}
        onPointerEnter={onPointerEnter}
        onPointerLeave={(e) => {
          longPress.onPointerLeave(e);
          onPointerLeave(e);
        }}
        onFocus={onFocus}
        onBlur={(e) => e.target === ref.current && hide(line.card_id)}
        className="tile flex min-h-10 w-full items-center gap-2.5 rounded-lg px-1.5 py-1 text-left outline-none transition-colors hover:bg-surface-2 focus-visible:bg-surface-2 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-accent/40 pointer-coarse:min-h-11"
      >
        <span ref={thumbRef} data-thumb className="block w-7 shrink-0">
          {card ? <CardImage card={card} kind="thumb" rounded="rounded" /> : <span className="block aspect-[5/7] w-full rounded bg-surface-3" aria-hidden />}
        </span>
        <span className="min-w-0 flex-1">
          <span className="block truncate text-[13px] font-medium leading-[17px] text-fg">{name}</span>
          <span className="block truncate text-[11px] leading-4 text-muted">
            <span className="tabular">{line.card_id}</span>
            {foil && <span className="foil-text ml-1.5 font-semibold">✦ foil</span>}
            {line.clamped && <span className="ml-1.5 text-warning">· clamped at 0</span>}
            {noteChanged && <span className="ml-1.5 italic">· note {line.note ? `“${line.note}”` : 'cleared'}</span>}
          </span>
        </span>
        {hasQty && (
          <span className="tabular flex shrink-0 items-center gap-1 text-[12.5px]">
            <span className="text-muted">{line.prev_qty}</span>
            <span className="text-faint" aria-hidden>
              →
            </span>
            <span className="font-semibold text-fg">{line.qty}</span>
            <span className={cx('ml-1 min-w-6 text-right font-semibold', delta > 0 ? 'text-success' : delta < 0 ? 'text-danger' : 'text-faint')}>{delta === 0 ? '·' : signed(delta)}</span>
          </span>
        )}
      </button>
    </li>
  );
}

function Lines({ lines, id }: { lines: FeedLine[]; id: string }) {
  const [all, setAll] = useState(false);
  const visible = all ? lines : lines.slice(0, LINE_CAP);
  return (
    <ol id={id} className="mt-1 flex flex-col" aria-label="Cards in this change">
      {visible.map((l, i) => (
        <LineRow key={`${l.card_id}:${l.finish ?? ''}:${i}`} line={l} />
      ))}
      {lines.length > visible.length && (
        <li>
          <button type="button" onClick={() => setAll(true)} className="mt-1 inline-flex min-h-8 items-center rounded-md px-1.5 text-xs font-medium text-accent hover:bg-accent/10 pointer-coarse:min-h-11">
            Show all {pluralize(lines.length, 'card')}
          </button>
        </li>
      )}
    </ol>
  );
}

// ---------------------------------------------------------------------------
// row
// ---------------------------------------------------------------------------

function ActorDot({ device }: { device: Change['device'] }) {
  if (device) return <Avatar name={device.name} color={device.color} size="sm" className="mt-0.5" />;
  return (
    <span role="img" aria-label="System" title="System" className="mt-0.5 inline-flex size-7 shrink-0 items-center justify-center rounded-full border border-border bg-surface-2 text-muted">
      <Cpu className="size-3.5" aria-hidden />
    </span>
  );
}

/** Secondary detail under the summary for non-card changes. */
function Detail({ change }: { change: Change }) {
  if (change.kind === 'tip') {
    const p = change.payload as TipPayload;
    return p.text ? <p className="mt-1 line-clamp-2 text-[12.5px] italic leading-snug text-muted">“{p.text}”</p> : null;
  }
  if (change.kind === 'settings') {
    const p = change.payload as SettingsPayload;
    return (
      <p className="tabular mt-1 text-[12px] leading-snug text-muted">
        playset {p.playset_size} · rune playset {p.rune_playset_size}
        {p.fx_manual_rate !== null ? ` · manual FX ${p.fx_manual_rate}` : ''}
        {p.collection_name ? ` · “${p.collection_name}”` : ''}
      </p>
    );
  }
  return null;
}

export interface ChangeItemProps {
  change: Change;
  /** Date.now() snapshot shared by the feed (relative times refresh together) */
  now: number;
  /** this row was made by the current device */
  mine: boolean;
  /** an undo for this row is in flight */
  busy: boolean;
  /** briefly emphasised after a jump */
  highlighted?: boolean;
  onUndo: (seq: number) => void;
  onJump: (seq: number) => void;
}

function ChangeItemInner({ change: c, now, mine, busy, highlighted, onUndo, onJump }: ChangeItemProps) {
  const cardsById = useStore((s) => s.cardsById);
  const [open, setOpen] = useState(false);
  const linesId = useId();

  const who = c.device?.name ?? 'System';
  const { text } = changeSummary(c, (id) => cardsById.get(id));
  // the actor is already shown in the header — drop the leading name from the one-liner
  const body = text.startsWith(`${who} `) ? text.slice(who.length + 1) : text;
  const kind = kindOf(c);
  const lines = linesOf(c);
  const canUndo = c.kind === 'inventory' && !c.undone;

  return (
    <li
      id={`change-${c.seq}`}
      data-seq={c.seq}
      aria-label={`#${c.seq}: ${text}`}
      className={cx('relative flex gap-3 px-3 py-2.5 transition-colors duration-300 sm:px-4', c.undone && 'opacity-60', highlighted && 'bg-accent/10')}
    >
      <ActorDot device={c.device} />
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-[12px] leading-5 text-muted">
          <span className="font-semibold text-fg">{who}</span>
          {mine && <span className="text-faint">(you)</span>}
          <Badge tone={KIND_TONE[kind]} size="xs" title={KIND_TITLE[kind]}>
            {kind}
          </Badge>
          {c.undone && (
            <Badge tone="outline" size="xs" title="This change was undone">
              undone
            </Badge>
          )}
          {c.undo_of !== null && (
            <button
              type="button"
              onClick={() => onJump(c.undo_of as number)}
              title={`Jump to change #${c.undo_of}`}
              className="inline-flex items-center gap-1 rounded-md px-1 text-[11.5px] text-accent hover:bg-accent/10 hover:text-accent-strong pointer-coarse:-my-3 pointer-coarse:min-h-11"
            >
              <CornerUpLeft className="size-3" aria-hidden />
              undo of #{c.undo_of}
            </button>
          )}
          <time dateTime={c.ts} title={`${fmtDateTime(c.ts)} · #${c.seq}`} className="tabular ml-auto shrink-0 text-[11.5px] text-faint">
            {relTime(c.ts, now)}
          </time>
        </div>
        <p className={cx('mt-0.5 text-[13.5px] leading-snug text-fg', c.undone && 'line-through decoration-faint')}>{body}</p>
        <Detail change={c} />
        {lines.length > 0 && (
          <div className="mt-1">
            <button
              type="button"
              aria-expanded={open}
              aria-controls={linesId}
              onClick={() => setOpen((o) => !o)}
              className="-ml-1 inline-flex min-h-7 items-center gap-1 rounded-md px-1 text-[12px] text-muted hover:bg-surface-2 hover:text-fg pointer-coarse:min-h-11"
            >
              <ChevronRight className={cx('size-3.5 transition-transform duration-150', open && 'rotate-90')} aria-hidden />
              {c.kind === 'tip' ? 'Show card' : pluralize(lines.length, 'card')}
            </button>
            {open && <Lines lines={lines} id={linesId} />}
          </div>
        )}
      </div>
      {canUndo && (
        <Button
          variant="ghost"
          size="sm"
          leftIcon={<Undo2 className="size-3.5" aria-hidden />}
          loading={busy}
          disabled={busy}
          onClick={() => onUndo(c.seq)}
          aria-label={`Undo change #${c.seq}`}
          className="-mr-1 self-start pointer-coarse:h-11 pointer-coarse:px-3"
        >
          Undo
        </Button>
      )}
    </li>
  );
}

export const ChangeItem = memo(ChangeItemInner);
